### ISSUE TITLE
All themes on a single page

### ISSUE THREAD

**Issue by kaushalmodi** [xyproto/splash#1]
Hello,

I was wondering if you can create just a single page that shows all the themes..

It would help someone quickly review all the themes. One example that I have in mind is a theme demo page for Pygments syntax highlighting: https://help.farbox.com/pygments.html.

**Comment by kaushalmodi** [comment]
Also can you update the code snippet to be more complex so that **all** different "faces" show up: keyword, function, variable, comment, string, digit, etc.

**Comment by xyproto** [comment]
Thanks for the feature request!

**Comment by kaushalmodi** [comment]
Thanks!

This looks great! https://xyproto.github.io/splash/docs/all.html

Also can you please update the code snippet to be more complex so that all different "faces" show up: keyword, function, variable, comment, string, digit, etc.

See the code complexity here as an example: http://peach-melpa.org/.

**Comment by xyproto** [comment]
Added a link to a style gallery with longer code samples. Please open separate issues for separate issues in the future.

[peach-melpa](http://peach-melpa.org/) looks pretty nice, thanks for the link.

**Comment by kaushalmodi** [comment]
> Please open separate issues for separate issues in the future.

Will do. I was just repeating my [earlier comment][1].

This looks great! https://xyproto.github.io/splash/docs/longer/all.html

Thanks!

[1]: https://github.com/xyproto/splash/issues/1#issuecomment-388465955
