### ISSUE TITLE
Catpuccin styles missing from Gallery

### ISSUE THREAD

**Issue by walles** [xyproto/splash#3]
From: https://github.com/alecthomas/chroma/issues/719

# Repro

1. Go here: https://xyproto.github.io/splash/docs/all.html
1. Search for `catpuccin`

# Current result

Not found

# Expected result

Four Catpuccin flavors should be on that page since it's in the Chroma source code:
https://github.com/alecthomas/chroma/tree/master/styles

**Comment by xyproto** [comment]
Thanks for reporting. Added the style.

**Comment by walles** [comment]
Chroma has four catppuccin flavors: https://github.com/alecthomas/chroma/tree/master/styles
* frappe
* latte
* macchiato
* mocha

The gallery has only one though ("catpuccin").

Do you think you could have the four flavors separately on the gallery page?

**Comment by xyproto** [comment]
I'll look into not having to add styles manually, and also having the webpage update automatically.

**Comment by xyproto** [comment]
I added a GitHub action that should run every night, look for updates in [the chroma repository](https://github.com/alecthomas/chroma/tree/master/styles), updates the `chroma` package, runs a small utility that extracts the list of styles and generates a new `styles.go` file, builds the `gendoc` utility that uses the new `styles.go` file and generates the HTML files, creates and pushes a new commit with the changes and also updates the web page at: https://xyproto.github.io/splash/docs/

This is a first attempt, so everything may not be working 100%. I see that some styles are not rendered correctly right now, but give it 24 hours and it might work out. If not, I'll look into it.

**Comment by xyproto** [comment]
Possibly related: #4

**Comment by xyproto** [comment]
After switching to chroma v2, the gallery now includes the four catpuccin styles.

https://xyproto.github.io/splash/docs/

Time will tell if the GitHub actions are set up correctly, though. :)
