### ISSUE TITLE
Add comments to the longer examples

### ISSUE THREAD

**Issue by CactiChameleon9** [xyproto/splash#5]
It would be nice if the longer examples included some form of comment (so we can see what that looks like)

**Comment by xyproto** [comment]
I agree. Thanks for the feature request!

**Comment by CactiChameleon9** [comment]
Thanks a lot for doing this, way more useful with comments :)

Sorry to nitpick - but the new longer examples are now quite long, which may be what you were after - but it does make it a little bit harder to compare if all the example doesn't all fit on a screen at once. On the other hand, it is more realistic to have a large bit of code covering the screen

**Comment by xyproto** [comment]
I agree. I shortened the long example code a bit. :+1:

**Comment by xyproto** [comment]
I also added you as collaborator, if other syntax highlighting related features should be missing from `cmd/gendoc/example/main.go`. The style gallery is updated automatically when the code is pushed, just so you know.

**Comment by CactiChameleon9** [comment]
Hey, thanks a bunch! I like the overall look for the longer examples page better with the slightly-shorter but long examples 

I have also never been added as a collaborator on gh before - so thats new. I have accepted, but I think it looks good to me
