### ISSUE TITLE
Gallery preview only displays two themes

### ISSUE THREAD

**Issue by icpmoles** [xyproto/splash#6]
As of now the [Chroma Style Gallery
](https://xyproto.github.io/splash/docs/) is only displaying xcode and xcode dark.

Looking at the commit history it seems like the problem comes and goes with every dependency update somehow.

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into it.

**Comment by nickjj** [comment]
In the mean time going to https://swapoff.org/chroma/playground/ offers a way to preview a specific language and theme. I'm not sure if it's 100% comparable to what the old gallery used to be here.

While selecting a highlighting style for Hugo I was able to take any name from that site and use it as the style name successfully.

**Comment by xyproto** [comment]
Fixed it. :heavy_check_mark:
